### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by JustSimplyKyle** [ishlandbukkit/RaiseSoundLimit#2]

**Comment by earthseekerx** [comment]
So should we wait or carry on with the bug?
Please respond with ETA if available.
Thank you

**Comment by toinouH** [comment]
I'm sorry but this is very very low priority that we can't give ETA (even if normally we already don't give them this is even harder to tell here).
I wish you a give day anyway.

**Comment by ishland** [comment]
This mod is deprecated, please consider using [RSLS](https://github.com/RelativityMC/raise-sound-limit-simplified)
